version: '3.1'

networks:
  dnd_data_network:

services:
  dnd-data:
    image: dnd-data:staging
    environment: 
      - "MONGODB_URI=mongodb://dbUser:password@mongo:27017/?retryWrites=true&w=majority"
    networks:
      - dnd_data_network
    depends_on:
      - mongo
    ports: 
      - 8000:8000
  mongo:
    image: mongo
    command: --serviceExecutor adaptive
    networks:
      - dnd_data_network
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=dbUser
      - MONGO_INITDB_ROOT_PASSWORD=password
