#!/usr/bin/with-contenv bash
ROOT_DIR=/app

# Replace env vars in JavaScript files
echo "Replacing env constants in JS"
for file in $ROOT_DIR/js/app.*.js* $ROOT_DIR/index.html;
do
  echo "Processing $file ...";

  sed -i 's|VUE_APP_API_URL|'http://localhost:8000/api/v1'|g' $file 
  # sed -i 's|VUE_APP_LOGO|'${LOGO}'|g' $file
  # sed -i 's|VUE_APP_VERSION|'${VERSION}'|g' $file

done
